import os
from typing import List
from shockwave.output.sarif_writer import ShockwaveFinding

REPORT_TEMPLATE = """# ShockWave Security Test Report

## Executive Summary

This report documents security findings discovered by **ShockWave** GraphQL security scanner.

| Severity | Count |
|---|---|
| Critical | {critical_count} |
| High | {high_count} |
| Medium | {medium_count} |
| Low | {low_count} |
| Info | {info_count} |
| **Total** | **{total_count}** |

---

## Detailed Findings

{detailed_findings}

---
*Report generated by ShockWave GraphQL Security Framework.*
"""

FINDING_TEMPLATE = """### [{severity}] {rule_name} ({rule_id})

- **OWASP API Category:** {owasp}
- **CWE Identifier:** {cwe}
- **Field Path:** `{field_path}`
- **Authentication Context:** `{auth_context}`
- **Confidence:** {confidence} (reproduced {confirmation_count} times)

#### Description
{remediation}

#### Evidence
**Request Query:**
```graphql
{evidence_request}
```

**Response Data (Snippet):**
```json
{evidence_response}
```

---
"""

def write_markdown_report(findings: List[ShockwaveFinding], output_dir: str) -> None:
    """Generates and writes a readable markdown report to the output directory."""
    os.makedirs(output_dir, exist_ok=True)
    
    crit = sum(1 for f in findings if f.severity.lower() == "critical")
    high = sum(1 for f in findings if f.severity.lower() == "high")
    med = sum(1 for f in findings if f.severity.lower() == "medium")
    low = sum(1 for f in findings if f.severity.lower() == "low")
    info = sum(1 for f in findings if f.severity.lower() == "info")
    
    details_list = []
    for f in findings:
        details_list.append(FINDING_TEMPLATE.format(
            severity=f.severity.upper(),
            rule_name=f.rule_name,
            rule_id=f.rule_id,
            owasp=f.owasp_category,
            cwe=f.cwe_id or "N/A",
            field_path=f.field_path,
            auth_context=f.auth_context or "None",
            confidence=f.confidence,
            confirmation_count=f.confirmation_count,
            remediation=f.remediation,
            evidence_request=f.evidence_request,
            evidence_response=f.evidence_response
        ))
        
    report_content = REPORT_TEMPLATE.format(
        critical_count=crit,
        high_count=high,
        medium_count=med,
        low_count=low,
        info_count=info,
        total_count=len(findings),
        detailed_findings="\n".join(details_list)
    )
    
    report_path = os.path.join(output_dir, "SECURITY_REPORT.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
