import httpx
from typing import Dict, Any, List, Optional
from shockwave.schema.models import GraphQLSchema
from shockwave.output.sarif_writer import ShockwaveFinding

async def scan_config(
    url: str,
    schema: GraphQLSchema,
    headers: Optional[Dict[str, str]] = None
) -> List[ShockwaveFinding]:
    """
    Checks for general configuration issues on the target server.
    """
    findings = []
    req_headers = {"Content-Type": "application/json"}
    if headers:
        req_headers.update(headers)

    # Finding 1: Introspection check
    # We send the introspection query to see if it responds with schema
    introspection_query = "query { __schema { types { name } } }"
    async with httpx.AsyncClient(verify=False) as client:
        try:
            res = await client.post(url, json={"query": introspection_query}, headers=req_headers, timeout=10)
            if res.status_code == 200 and "__schema" in str(res.json()):
                findings.append(ShockwaveFinding(
                    id="",  # Generated by sarif writer if empty
                    rule_id="SHOCKWAVE-CONF-001",
                    rule_name="Introspection enabled in production",
                    severity="info",
                    owasp_category="API8:2023 — Security Misconfiguration",
                    cwe_id="CWE-16",
                    field_path="Schema",
                    engine="Generic",
                    evidence_request=f"POST {url} with query: {introspection_query}",
                    evidence_response=str(res.json())[:500],
                    auth_context="No Auth" if not headers else "Provided Auth",
                    confidence="confirmed",
                    confirmation_count=1,
                    remediation="Disable introspection in production environments (e.g. set introspection: false in Apollo Server configuration).",
                    references=["https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#introspection"]
                ))
        except Exception:
            pass

        # Finding 2: Field suggestions check
        suggestion_query = "query { __non_existent_field_suggestion_probe }"
        try:
            res = await client.post(url, json={"query": suggestion_query}, headers=req_headers, timeout=10)
            res_data = res.json()
            errors = res_data.get("errors", [])
            has_suggestion = False
            for err in errors:
                if "Did you mean" in err.get("message", ""):
                    has_suggestion = True
                    break
            if has_suggestion:
                findings.append(ShockwaveFinding(
                    id="",
                    rule_id="SHOCKWAVE-CONF-002",
                    rule_name="Field suggestions enabled",
                    severity="info",
                    owasp_category="API8:2023 — Security Misconfiguration",
                    cwe_id="CWE-200",
                    field_path="Schema",
                    engine="Generic",
                    evidence_request=f"POST {url} with query: {suggestion_query}",
                    evidence_response=str(res_data)[:500],
                    auth_context="No Auth" if not headers else "Provided Auth",
                    confidence="confirmed",
                    confirmation_count=1,
                    remediation="Disable field suggestion error messages in production. In Apollo Server, use plugins or custom formatError to strip suggestions.",
                    references=["https://cheatsheetseries.owasp.org/cheatsheets/GraphQL_Cheat_Sheet.html#disable-suggestions"]
                ))
        except Exception:
            pass

    return findings
